-- PR-031: anonymous search insights and administrative aggregates.

CREATE TABLE IF NOT EXISTS public.search_insights (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query_normalized text NOT NULL CHECK (char_length(query_normalized) BETWEEN 2 AND 80),
  result_count integer NOT NULL CHECK (result_count BETWEEN 0 AND 48),
  searched_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS search_insights_searched_at_idx
  ON public.search_insights (searched_at DESC);
CREATE INDEX IF NOT EXISTS search_insights_query_time_idx
  ON public.search_insights (query_normalized, searched_at DESC);
CREATE INDEX IF NOT EXISTS search_insights_zero_results_idx
  ON public.search_insights (searched_at DESC, query_normalized)
  WHERE result_count = 0;

ALTER TABLE public.search_insights ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.search_insights FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.record_search_insight(
  p_query text,
  p_result_count integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_query text;
  v_result_count integer;
BEGIN
  v_query := lower(left(btrim(regexp_replace(COALESCE(p_query, ''), '\s+', ' ', 'g')), 80));
  v_result_count := LEAST(GREATEST(COALESCE(p_result_count, 0), 0), 48);

  IF char_length(v_query) < 2 THEN
    RETURN false;
  END IF;

  INSERT INTO public.search_insights (query_normalized, result_count)
  VALUES (v_query, v_result_count);

  RETURN true;
END;
$$;

REVOKE ALL ON FUNCTION public.record_search_insight(text, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_search_insight(text, integer) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_search_operations_snapshot(
  p_days integer DEFAULT 30,
  p_limit integer DEFAULT 10
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_days integer := LEAST(GREATEST(COALESCE(p_days, 30), 1), 365);
  v_limit integer := LEAST(GREATEST(COALESCE(p_limit, 10), 1), 25);
  v_since timestamptz;
  v_top_queries jsonb;
  v_no_result_queries jsonb;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Administrator access required' USING ERRCODE = '42501';
  END IF;

  v_since := now() - make_interval(days => v_days);

  SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY r.searches DESC, r.query), '[]'::jsonb)
  INTO v_top_queries
  FROM (
    SELECT
      query_normalized AS query,
      count(*)::integer AS searches,
      round(avg(result_count)::numeric, 1) AS average_results,
      max(searched_at) AS last_searched_at
    FROM public.search_insights
    WHERE searched_at >= v_since
    GROUP BY query_normalized
    ORDER BY count(*) DESC, query_normalized
    LIMIT v_limit
  ) r;

  SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY r.searches DESC, r.query), '[]'::jsonb)
  INTO v_no_result_queries
  FROM (
    SELECT
      query_normalized AS query,
      count(*)::integer AS searches,
      max(searched_at) AS last_searched_at
    FROM public.search_insights
    WHERE searched_at >= v_since AND result_count = 0
    GROUP BY query_normalized
    ORDER BY count(*) DESC, query_normalized
    LIMIT v_limit
  ) r;

  RETURN jsonb_build_object(
    'indexed_documents', (SELECT count(*) FROM public.search_documents WHERE publish_at IS NULL OR publish_at <= now()),
    'eligible_products', (SELECT count(*) FROM public.products WHERE status = 'published' AND (publish_at IS NULL OR publish_at <= now())),
    'pending_documents', GREATEST(
      (SELECT count(*) FROM public.products WHERE status = 'published' AND (publish_at IS NULL OR publish_at <= now()))
      - (SELECT count(*) FROM public.search_documents WHERE publish_at IS NULL OR publish_at <= now()),
      0
    ),
    'last_indexed_at', (SELECT max(updated_at) FROM public.search_documents WHERE publish_at IS NULL OR publish_at <= now()),
    'period_days', v_days,
    'total_searches', (SELECT count(*) FROM public.search_insights WHERE searched_at >= v_since),
    'zero_result_searches', (SELECT count(*) FROM public.search_insights WHERE searched_at >= v_since AND result_count = 0),
    'distinct_queries', (SELECT count(DISTINCT query_normalized) FROM public.search_insights WHERE searched_at >= v_since),
    'last_search_at', (SELECT max(searched_at) FROM public.search_insights WHERE searched_at >= v_since),
    'top_queries', v_top_queries,
    'no_result_queries', v_no_result_queries
  );
END;
$$;

REVOKE ALL ON FUNCTION public.get_search_operations_snapshot(integer, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_search_operations_snapshot(integer, integer) TO authenticated;
