-- ===================== DETALHAMENTO INTERNO =====================
INSERT INTO products (name, slug, short_description, description, image_url, gallery_images, category_id, brand_id, status, is_new, is_featured, rating, review_count, specifications) VALUES
('Couro QD Quick Detail 2 em 1 EasyTech 500ml', 'couro-qd-easytech-500ml',
'Limpa e hidrata couro em uma única etapa. Seguro para couro natural ou sintético.',
'Couro QD limpa e hidrata couro em uma única etapa. Desenvolvido para uso rápido, promove limpeza segura sem riscos de remoção de pigmentos do couro por uso de produtos agressivos, ao mesmo tempo que garante a hidratação do material. Contém óleos hidratantes de baixo peso molecular. Aplicação em couro natural, couro sintético e plásticos.',
'https://images.tcdn.com.br/img/img_prod/1152560/couro_qd_quick_detail_2_em_1_limpa_e_hidrata_easytech_500ml_1139_1_a6831e1a70777a792a124f8fae32bfb5.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/couro_qd_quick_detail_2_em_1_limpa_e_hidrata_easytech_500ml_1139_1_a6831e1a70777a792a124f8fae32bfb5.jpg","https://images.tcdn.com.br/img/img_prod/1152560/couro_qd_quick_detail_2_em_1_limpa_e_hidrata_easytech_500ml_1139_2_26ad7af8ed8354a0e41494642d3ea80d.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', '16ed7769-be17-4581-8fbd-90a4d5d6499b', 'published', false, true, 5.0, 3,
'{"Volume":"500ml","Tipo":"Limpa e Hidrata Couro","Aplicação":"Couro natural, sintético e plásticos","Marca":"EasyTech"}'),

('SOUL Hidratante de Couro EasyTech 500ml', 'soul-hidratante-couro-easytech-500ml',
'Hidratante de couro à base de lanolina, óleo de amêndoas e aloe vera. Acabamento seco e toque macio.',
'Soul é um hidratante de couro desenvolvido à base de substratos nobres, baseado em Lanolina, óleo de amêndoas e óleo de aloe vera. Soul tem um acabamento seco e toque macio, hidratando o couro sem deixá-lo gorduroso. Ideal para manutenção de couros natural e sintético.',
'https://images.tcdn.com.br/img/img_prod/1152560/soul_hidratante_de_couro_sintetico_e_natural_easytech_500ml_28286_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/soul_hidratante_de_couro_sintetico_e_natural_easytech_500ml_28286_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', '16ed7769-be17-4581-8fbd-90a4d5d6499b', 'published', false, false, 4.5, 2,
'{"Volume":"500ml","Tipo":"Hidratante de Couro","Composição":"Lanolina, óleo de amêndoas, aloe vera","Marca":"EasyTech"}'),

('Interior Cleaner Limpador Multiuso Sonax 500ml', 'interior-cleaner-sonax-500ml',
'APC que limpa profundamente sem agredir as superfícies do interior do veículo.',
'Interior Cleaner Limpador Multiuso Sonax é um APC que limpa profundamente sem agredir as superfícies do interior do veículo, mesmo sujeiras como graxa, óleo e manchas difíceis. Ideal para painéis, bancos, portas e demais superfícies internas.',
'https://images.tcdn.com.br/img/img_prod/1152560/refil_interior_cleaner_limpador_multiuso_sonax_500ml_25956_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/refil_interior_cleaner_limpador_multiuso_sonax_500ml_25956_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', 'e2b10d5e-82fd-46ee-bc1c-da5c8d8a1788', 'published', false, false, 4.0, 1,
'{"Volume":"500ml","Tipo":"APC Limpador Multiuso","Marca":"Sonax","Origem":"Alemanha"}'),

('Hidrata Couro Finisher 160g', 'hidrata-couro-finisher-160g',
'Hidratante que revela a cor original, aumenta a maciez e previne rachaduras no couro automotivo.',
'Hidrata Couro Finisher revela a cor original, aumenta a maciez e previne rachaduras no couro automotivo. Produto ideal para conservar bancos e acessórios de couro, mantendo a aparência e flexibilidade do material.',
'https://images.tcdn.com.br/img/img_prod/1152560/hidrata_couro_finisher_150g_27329_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/hidrata_couro_finisher_150g_27329_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', 'ea720c10-751e-4e7a-a83c-547e3152d45c', 'published', false, false, 4.0, 1,
'{"Peso":"160g","Tipo":"Hidratante de Couro","Marca":"Autoshine"}'),

('Renovador de Couro Autoshine 5L', 'renovador-couro-autoshine-5l',
'Renovador que hidrata, limpa e protege o couro, devolvendo a aparência original.',
'O Renovador de Couro Autoshine foi desenvolvido para hidratar, limpar e proteger o tecido derivado de animais, que com a ação do tempo perde a aparência original. Devolve maciez, cor e brilho ao couro automotivo.',
'https://images.tcdn.com.br/img/img_prod/1152560/renovador_de_couro_autoshine_5_litros_25982_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/renovador_de_couro_autoshine_5_litros_25982_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', 'ea720c10-751e-4e7a-a83c-547e3152d45c', 'published', false, false, 4.0, 1,
'{"Volume":"5 Litros","Tipo":"Renovador de Couro","Marca":"Autoshine"}'),

('LL1 APC Limpador Multiuso Concentrado Lincoln 1L', 'll1-apc-limpador-multiuso-lincoln-1l',
'Limpador multiuso de alta performance para sujeiras orgânicas e inorgânicas com mínimo esforço.',
'O APC LL1 é um limpador multiuso de alta performance, elaborado para limpar profundamente sujeiras orgânicas e inorgânicas, com o mínimo esforço e com a máxima segurança. Diluição variável conforme a intensidade da sujeira.',
'https://images.tcdn.com.br/img/img_prod/1152560/ll1_apc_all_purpose_cleaner_limpador_multiuso_lincoln_1_litro_27810_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/ll1_apc_all_purpose_cleaner_limpador_multiuso_lincoln_1_litro_27810_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', '791f9478-d15a-4863-966b-90777fa6bfb0', 'published', false, true, 4.5, 2,
'{"Volume":"1 Litro","Tipo":"APC Limpador Multiuso","Diluição":"Variável","Marca":"Lincoln"}'),

('PLURI Super APC Alcalino EasyTech 5L', 'pluri-apc-alcalino-easytech-5l',
'Multilimpador APC alcalino para limpeza pesada e desengraxe. Concentrado com diluição até 1:50.',
'Multilimpador APC PLURI é um limpador multifuncional destinado à remoção de sujeiras pesadas e desengraxe. PLURI é concentrado e de baixa viscosidade, fácil de diluir. Indicado para limpeza de motores, rodas, superfícies internas e externas.',
'https://images.tcdn.com.br/img/img_prod/1152560/pluri_multilimpador_alcalino_limpeza_pesada_easytech_5_litros_diluicao_ate_1_50_27637_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/pluri_multilimpador_alcalino_limpeza_pesada_easytech_5_litros_diluicao_ate_1_50_27637_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', '16ed7769-be17-4581-8fbd-90a4d5d6499b', 'published', false, false, 4.5, 2,
'{"Volume":"5 Litros","Tipo":"APC Alcalino","Diluição":"Até 1:50","Marca":"EasyTech"}'),

('Multi X APC Concentrado CarPro 500ml', 'multi-x-apc-carpro-500ml',
'Limpador APC concentrado de alta performance para detalhamento automotivo.',
'Limpador APC concentrado CarPro, formulado para limpeza profunda de múltiplas superfícies. Versátil e eficiente, pode ser diluído em diferentes proporções conforme a aplicação desejada.',
'https://images.tcdn.com.br/img/img_prod/1152560/multi_x_apc_concentrado_carpro_500_ml_28358_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/multi_x_apc_concentrado_carpro_500_ml_28358_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', '932d8081-e1dc-49e9-921d-2524688ee6a1', 'published', false, false, 4.0, 1,
'{"Volume":"500ml","Tipo":"APC Concentrado","Marca":"CarPro"}'),

('Limpador Multiação APC Vintex 500ml', 'limpador-multiacao-apc-vintex-500ml',
'Limpador multiação que remove sujeiras difíceis com segurança. Formulação balanceada.',
'O Limpador Multiação Vintex foi desenvolvido para remover sujeiras mais difíceis e de diversas naturezas. Remove gorduras, manchas e encardidos de bancos, tetos, painéis e laterais de porta com segurança.',
'https://images.tcdn.com.br/img/img_prod/1152560/limpador_multiacao_apc_vintex_5_litros_diluicao_1_5_28628_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/limpador_multiacao_apc_vintex_5_litros_diluicao_1_5_28628_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', 'd4f656fc-78dd-4f8e-a792-0e64df4b49ab', 'published', false, false, 4.0, 1,
'{"Volume":"500ml","Tipo":"APC Limpador Multiação","Diluição":"1:5","Marca":"Vintex"}'),

('Insignia Leather Nano Proteção EasyTech 30ml', 'insignia-leather-easytech-30ml',
'Nano proteção com hidratação para couro. Sujeiras ficam sob a camada de proteção, removidas facilmente.',
'Insignia Leather oferece nano proteção com hidratação para couro. As sujeiras que normalmente ficam incrustadas no couro ficam sob a camada de proteção, sendo facilmente removidas sem uso de produtos químicos. Proteção de longa duração.',
'https://images.tcdn.com.br/img/img_prod/1152560/insignia_leather_nano_protecao_com_hidratacao_para_couro_easytech_30ml_29328_1.jpg',
'["https://images.tcdn.com.br/img/img_prod/1152560/insignia_leather_nano_protecao_com_hidratacao_para_couro_easytech_30ml_29328_1.jpg"]',
'fc57ced6-8e7f-449e-860d-6fd7fcab1081', '16ed7769-be17-4581-8fbd-90a4d5d6499b', 'published', true, false, 5.0, 1,
'{"Volume":"30ml","Tipo":"Nano Proteção de Couro","Marca":"EasyTech"}')
ON CONFLICT (slug) DO NOTHING;
