import type { BlogPost } from '../types'

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Guia completo de lavagem segura: evite riscos na pintura',
    slug: 'guia-lavagem-segura',
    excerpt: 'Aprenda o método dos dois baldes, a escolha do shampoo ideal e os erros mais comuns que causam swirl marks na sua pintura.',
    cover_image: null,
    author: 'Equipe PapoDetailer',
    published_at: '2024-11-15T10:00:00Z',
    tags: ['lavagem', 'iniciante', 'shampoo'],
    content: `A lavagem segura é o primeiro passo para manter a pintura do seu veículo em perfeito estado.\n\n## O método dos dois baldes\n\nO método dos dois baldes é uma técnica fundamental para evitar que sujeira seja reintroduzida na pintura durante a lavagem.\n\nUse um balde para a água com shampoo e outro com água limpa para enxaguar a luva microfibra antes de mergulhá-la novamente no shampoo.\n\n## Escolhendo o shampoo certo\n\nPrefira shampoos com pH neutro, que não agridem ceras, selantes e coatings existentes. Evite detergentes de cozinha, que removem toda a proteção da pintura.\n\n## Erros comuns\n\n- Lavar o veículo sob sol direto\n- Usar esponjas comuns\n- Secar com toalhas inadequadas\n- Não usar lubrificação suficiente`,
  },
  {
    id: '2',
    title: 'Cera, selante ou coating: qual proteção escolher?',
    slug: 'cera-selante-ou-coating',
    excerpt: 'Entenda as diferenças entre os três principais tipos de proteção de pintura e qual se adequa melhor ao seu perfil.',
    cover_image: null,
    author: 'Equipe PapoDetailer',
    published_at: '2024-10-28T10:00:00Z',
    tags: ['proteção', 'cera', 'selante', 'coating'],
    content: `A escolha da proteção ideal depende do seu perfil de uso, orçamento e nível de dedicação.\n\n## Cera\n\nA cera oferece o brilho mais profundo e natural, com duração de 1 a 3 meses. É a preferida de entusiastas que gostam do ritual de aplicação.\n\n## Selante\n\nSelantes sintéticos duram de 3 a 6 meses, oferecem melhor resistência química e são mais fáceis de aplicar.\n\n## Coating cerâmico\n\nCoatings oferecem durabilidade de 1 a 5 anos, resistência química superior e hidrorrepelência excepcional. Requerem preparação cuidadosa da pintura.`,
  },
  {
    id: '3',
    title: 'Polimento: do corte ao acabamento em 5 passos',
    slug: 'polimento-corte-acabamento',
    excerpt: 'Um guia prático para iniciantes no polimento automotivo, abordando máquina, boinas, compostos e técnica.',
    cover_image: null,
    author: 'Equipe PapoDetailer',
    published_at: '2024-10-10T10:00:00Z',
    tags: ['polimento', 'correção', 'pintura'],
    content: `O polimento é a técnica de correção de defeitos na pintura através do uso de abrasivos.\n\n## 1. Avaliação\n\nIdentifique o tipo de defeito: swirl marks, riscos profundos, oxidação ou hologramas.\n\n## 2. Escolha da máquina\n\nRoto-orbitais são mais seguras para iniciantes. Rotativas exigem mais experiência.\n\n## 3. Boinas\n\nComece com boina de corte e composto pesado, depois refine com boina de acabamento e polidor fino.\n\n## 4. Técnica\n\nMovimentos lentos e cruzados, mantendo a área de trabalho controlada.\n\n## 5. Proteção\n\nApós o polimento, aplique uma camada de proteção para preservar o resultado.`,
  },
  {
    id: '4',
    title: 'Detalhamento de interiores: couro, plástico e tecido',
    slug: 'detalhamento-interiores',
    excerpt: 'Como cuidar de cada tipo de superfície interna do veículo, preservando o aspecto e a durabilidade dos materiais.',
    cover_image: null,
    author: 'Equipe PapoDetailer',
    published_at: '2024-09-22T10:00:00Z',
    tags: ['interiores', 'couro', 'plástico'],
    content: `O detalhamento de interiores requer produtos específicos para cada material.\n\n## Couro\n\nUse produtos hidratantes específicos para couro automotivo. Evite produtos com silicone que podem ressecar.\n\n## Plástico\n\nPara plásticos, prefira produtos que nutrem sem deixar aspecto oleoso. O acabamento fosco é mais elegante.\n\n## Tecido e carpete\n\nUse extratora ou vaporizador para limpeza profunda. Produtos com pH adequado evitam manchas.`,
  },
  {
    id: '5',
    title: 'Como escolher o aromatizante ideal para seu carro',
    slug: 'aromatizante-ideal',
    excerpt: 'Famílias olfativas, intensidade e formato: tudo o que você precisa saber para escolher o aromatizante perfeito.',
    cover_image: null,
    author: 'Equipe PapoDetailer',
    published_at: '2024-09-05T10:00:00Z',
    tags: ['aromatizante', 'fragrância', 'interiores'],
    content: `O aromatizante certo transforma a experiência a bordo.\n\n## Famílias olfativas\n\n- Cítricos: refrescantes e energizantes\n- Amadeirados: sofisticados e duradouros\n- Florais: suaves e elegantes\n- Doces: envolventes e aconchegantes\n\n## Intensidade\n\nConsidere o tamanho do veículo. Carros pequenos pedem fragrâncias mais suaves.\n\n## Formato\n\nLíquidos, sólidos e difusores elétricos: cada formato tem sua vantagem em durabilidade e projeção.`,
  },
  {
    id: '6',
    title: 'Cristalização de vidros: hidrorrepelência que faz diferença',
    slug: 'cristalizacao-vidros',
    excerpt: 'Como a cristalização de vidros melhora a visibilidade em chuva e facilita a limpeza do para-brisa.',
    cover_image: null,
    author: 'Equipe PapoDetailer',
    published_at: '2024-08-18T10:00:00Z',
    tags: ['vidros', 'cristalização', 'hidrorrepelência'],
    content: `A cristalização de vidros cria uma camada hidrorrepelente que faz a água escorrer facilmente.\n\n## Benefícios\n\n- Melhor visibilidade em chuva\n- Maior facilidade de limpeza\n- Redução do uso do limpador\n- Proteção contra manchas de água\n\n## Aplicação\n\nA preparação é fundamental: desengraxe completo do vidro antes da aplicação.\n\n## Durabilidade\n\nProdutos de qualidade oferecem de 3 a 6 meses de proteção.`,
  },
]
