/*
# Affiliate click attribution

Records outbound affiliate clicks without collecting personal identifiers.
Public clients can only call the validated RPC; raw table inserts and reads remain blocked.
Administrators can read aggregated and row-level click data through existing admin authorization.
*/

CREATE TABLE IF NOT EXISTS public.affiliate_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  affiliate_link_id uuid NOT NULL REFERENCES public.affiliate_links(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  page_path text NOT NULL,
  referrer_domain text,
  clicked_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS affiliate_clicks_link_clicked_at_idx
  ON public.affiliate_clicks(affiliate_link_id, clicked_at DESC);
CREATE INDEX IF NOT EXISTS affiliate_clicks_product_clicked_at_idx
  ON public.affiliate_clicks(product_id, clicked_at DESC);
CREATE INDEX IF NOT EXISTS affiliate_clicks_clicked_at_idx
  ON public.affiliate_clicks(clicked_at DESC);

ALTER TABLE public.affiliate_clicks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_select_affiliate_clicks" ON public.affiliate_clicks;
CREATE POLICY "admin_select_affiliate_clicks"
  ON public.affiliate_clicks
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

CREATE OR REPLACE FUNCTION public.track_affiliate_click(
  p_affiliate_link_id uuid,
  p_page_path text,
  p_referrer_domain text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
VOLATILE
SET search_path = ''
AS $$
DECLARE
  v_product_id uuid;
BEGIN
  SELECT affiliate_links.product_id
    INTO v_product_id
  FROM public.affiliate_links
  WHERE affiliate_links.id = p_affiliate_link_id;

  IF v_product_id IS NULL THEN
    RETURN;
  END IF;

  INSERT INTO public.affiliate_clicks (
    affiliate_link_id,
    product_id,
    page_path,
    referrer_domain
  ) VALUES (
    p_affiliate_link_id,
    v_product_id,
    LEFT(COALESCE(NULLIF(TRIM(p_page_path), ''), '/'), 500),
    NULLIF(LEFT(TRIM(COALESCE(p_referrer_domain, '')), 255), '')
  );
END;
$$;

REVOKE ALL ON FUNCTION public.track_affiliate_click(uuid, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.track_affiliate_click(uuid, text, text) TO anon, authenticated;